IUT_CS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('home/', views.home.as_view(), name='home_'),
                  path('mdeditor/', include('mdeditor.urls')),
                  path('blogs/', include('blogs.urls')),
                  path('achievements/', include('achievements.urls')),
                  path('activity/', include('activity.urls')),
                  path('executive_committee/', views.ExecutiveCommittee.as_view(), name='executive_committee'),
                  path('about/', views.about.as_view(), name='about'),
                  path('admin_panel/', include('admin_panel.urls')),
                  path('intra_events/', include('intra_university_event.urls')),
                  path('inter_events/', include('inter_university_event.urls')),
                  path('events/', views.events.as_view(), name='events'),
                  path('', views.home.as_view(), name='home'),
                  path('inter_events_and_participants/', views.inter_event_participants.as_view(), name='inter_events_and_participants'),
                  path('intra_events_and_participants/', views.intra_event_participants.as_view(), name='intra_events_and_participants'),
                  path('leaderboard/', views.leaderboard.as_view(), name='leaderboard'),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

achievements/urls.py
from django.urls import path

from . import views

app_name = 'achievements'

urlpatterns = [
    path('', views.index, name='achievements'),
    path('create_achievement/', views.createAchievement, name='create_achievement'),
    path('edit_achievement/<int:pk>', views.editAchievement.as_view(), name='edit_Achievement'),
    path('update_achievement/<int:pk>', views.updateAchievement, name='update_Achievement'),
    path('delete_achievement/<int:pk>', views.deleteAchievement, name='delete_Achievement'),
]

activity/urls.py
from django.urls import path

from . import views

app_name = 'activity'

urlpatterns = [
    path('', views.index, name='activity'),
    path('create_activity/', views.createActivity, name='create_activity'),
    path('edit_activity/<int:pk>', views.editActivity.as_view(), name='edit_activity'),
    path('update_activity/<int:pk>', views.updateActivity, name='update_activity'),
    path('delete_activity/<int:pk>', views.deleteActcity, name='delete_activity'),
]

admin_panel/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

#app_name = 'admin_panel'

urlpatterns = [
    # Login and Logout
    path('', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='admin_panel/login.html'), name='login'),
    path('all/',views.AdminPanel,name='admin_panel'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),

]

blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name='blogs'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create_blog/', views.createBlog, name='create_blog'),
    path('edit_blog/<int:pk>', views.editBlog.as_view(), name='edit_blog'),
    path('update_blog/<int:pk>', views.updateBlog, name='update_blog'),
    path('delete_blog/<int:pk>', views.deleteBlog, name='delete_blog'),
]

inter_university_event/urls.py
from django.urls import path

from . import views

app_name = 'inter_event'

urlpatterns = [
    path('', views.index, name='inter_events'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create_inter_event/', views.createInter_event, name='create_event'),
    path('edit_inter_event/<int:pk>', views.editInter_event.as_view(), name='edit_event'),
    path('update_inter_event/<int:pk>', views.updateInter_event, name='update_event'),
    path('delete_inter_event/<int:pk>', views.deleteInter_event, name='delete_event'),
    path('team_registration/<int:pk>', views.team_registration, name='team_registration'),
    
]

'''

'''

intra_university_event/urls.py
from django.urls import path

from . import views

app_name = 'intra_event'

urlpatterns = [
    path('', views.index, name='intra_events'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create_intra_event/', views.createIntra_event, name='create_event'),
    path('edit_intra_event/<int:pk>', views.editIntra_event.as_view(), name='edit_event'),
    path('update_intra_event/<int:pk>', views.updateIntra_event, name='update_event'),
    path('google_form_intra_event/<int:pk>', views.google_formIntra_event, name='google_form'),
    path('delete_intra_event/<int:pk>', views.deleteIntra_event, name='delete_event'),
]

'''

'''

admin_panel/views.py
import os

from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect
from django.views.generic import TemplateView

from achievements.models import Achievement

# Create your views here.
def AdminPanel(request):
    return render(request, 'admin_panel/index.html')

admin_panel/templates/admin_panel/index.html
{% extends 'base.html' %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="/static/styles/main.css">
<link rel="stylesheet" type="text/css" href="/static/styles/admin-panel.css">
    <div class="container">
        <br>
        <br>
        <br>
        <br>

        <!-- Blog Section -->
<section id="blog" class="section">
    <!-- Container Starts -->
    <div class="container">
      <div class="section-header">
        <h2 class="section-title">Admin Panel</h2>
        <span>Edit Access</span>
        <p class="section-subtitle">Elevate Your Control: Mastering Edits with Precision on Our Admin Panel!</p>
        
        <a href={% url 'logout' %}>
          <button type="button" class="edit-button1">Logout</button>
        </a>

      </div>
      <div class="row">
        <div class="col-lg-4 col-md-6 col-xs-12 blog-item">
          <!-- Blog Item Starts -->
          <div class="blog-item-wrapper">
            <div class="blog-item-img">
                <img src="/media/admin_panel/achiv.jpg" alt="">
            </div>
            <!-- <div class="blog-item-text">
              <h3><a href="single-post.html">Create Achivements</a></h3>
            </div> -->

            <a href={% url 'achievements:create_achievement' %}>
                <!-- <button type="button">Create Achievement</button> -->
                <button type="button" class="edit-button">Create Achievement</button>
            </a>

          </div>
          <!-- Blog Item Wrapper Ends-->
        </div>

        <div class="col-lg-4 col-md-6 col-xs-12 blog-item">
          <!-- Blog Item Starts -->
          <div class="blog-item-wrapper">
            <div class="blog-item-img">
                <img src="/media/admin_panel/acti.jpg" alt="">
            </div>
            <!-- <div class="blog-item-text">
              <h3><a href="single-post.html">ICT Fest - Inter university program</a></h3>
            </div> -->

            <a href={% url 'activity:create_activity' %}>
                <!-- <button type="button">Create Achievement</button> -->
                <button type="button" class="edit-button">Create Activity</button>
            </a>

          </div>
        </div>

        <div class="col-lg-4 col-md-6 col-xs-12 blog-item">
            <!-- Blog Item Starts -->
            <div class="blog-item-wrapper">
              <div class="blog-item-img">
                  <img src="/media/admin_panel/blg.jpg" alt="">
              </div>
              <!-- <div class="blog-item-text">
                <h3><a href="single-post.html">ICT Fest - Inter university program</a></h3>
              </div> -->

              <a href={% url 'blogs:create_blog' %}>
                  <!-- <button type="button">Create Achievement</button> -->
                  <button type="button" class="edit-button">Create Blog</button>
              </a>

            </div>
          </div>
      </div>
    </div>



        <br>
        <br>
        <br>
      <div class="container">
        <div class="col-lg-4 col-md-6 col-xs-12 blog-item">
          <!-- Blog Item Starts -->
          <div class="blog-item-wrapper">
            <div class="blog-item-img">
                <img src="/media/admin_panel/intra_event.jpg" alt="">
            </div>
            <a href={% url 'intra_event:create_event' %}>
              <button type="button" class="edit-button">Create intra university event</button>
          </a>
          </div>
        </div>

    <div class="col-lg-4 col-md-6 col-xs-12 blog-item">
      <!-- Blog Item Starts -->
      <div class="blog-item-wrapper">
        <div class="blog-item-img">
            <img src="/media/admin_panel/event.png" alt="">
        </div>
        <a href={% url 'inter_event:create_event' %}>
            <button type="button" class="edit-button">Create inter university event</button>
        </a>
      </div>
    </div>

    <div class="col-lg-4 col-md-6 col-xs-12 blog-item">
      <!-- Blog Item Starts -->
      <div class="blog-item-wrapper">
        <div class="blog-item-img">
            <img src="/media/admin_panel/participation.png" alt="">
        </div>
        <a href={% url 'inter_events_and_participants' %}>
          <button type="button" class="edit-button">View Inter Event Participants</button>
      </a>
      </div>
    </div>
    </div>

    <br>
    <br>
    <div class="container">
      <div class="col-lg-4 col-md-6 col-xs-12 blog-item">
        <!-- Blog Item Starts -->
        <div class="blog-item-wrapper">
          <div class="blog-item-img">
              <img src="/media/admin_panel/parti.png" alt="">
          </div>
          <a href={% url 'intra_events_and_participants' %}>
            <button type="button" class="edit-button">View Intra Event Participants</button>
        </a>
        </div>
      </div>
    </div>

  </section>

  </div>



{% endblock content %}

admin_panel/templates/admin_panel/login.html
{% extends 'base.html' %}

{% block title %}Login Page{% endblock title %}

{% block content %} 
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock content %}