IUT_CS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('home/', views.home.as_view(), name='home_'),
                  path('mdeditor/', include('mdeditor.urls')),
                  path('blogs/', include('blogs.urls')),
                  path('achievements/', include('achievements.urls')),
                  path('activity/', include('activity.urls')),
                  path('executive_committee/', views.ExecutiveCommittee.as_view(), name='executive_committee'),
                  path('about/', views.about.as_view(), name='about'),
                  path('admin_panel/', include('admin_panel.urls')),
                  path('intra_events/', include('intra_university_event.urls')),
                  path('inter_events/', include('inter_university_event.urls')),
                  path('events/', views.events.as_view(), name='events'),
                  path('', views.home.as_view(), name='home'),
                  path('inter_events_and_participants/', views.inter_event_participants.as_view(), name='inter_events_and_participants'),
                  path('intra_events_and_participants/', views.intra_event_participants.as_view(), name='intra_events_and_participants'),
                  path('leaderboard/', views.leaderboard.as_view(), name='leaderboard'),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

activity/urls.py
from django.urls import path

from . import views

app_name = 'activity'

urlpatterns = [
    path('', views.index, name='activity'),
    path('create_activity/', views.createActivity, name='create_activity'),
    path('edit_activity/<int:pk>', views.editActivity.as_view(), name='edit_activity'),
    path('update_activity/<int:pk>', views.updateActivity, name='update_activity'),
    path('delete_activity/<int:pk>', views.deleteActcity, name='delete_activity'),
]

blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name='blogs'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create_blog/', views.createBlog, name='create_blog'),
    path('edit_blog/<int:pk>', views.editBlog.as_view(), name='edit_blog'),
    path('update_blog/<int:pk>', views.updateBlog, name='update_blog'),
    path('delete_blog/<int:pk>', views.deleteBlog, name='delete_blog'),
]

activity/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
    title = models.CharField(max_length=256)
    time = models.DateTimeField()
    description = models.TextField()

activity/views.py
import os

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from django.views.generic import TemplateView

from .models import Activity


# Create your views here.

def index(request):
    activity = Activity.objects.all()
    context = {'activity': activity}

    return render(request, 'activity/index.html', context)


def createActivity(request):
    if request.method == 'POST':
        if request.POST.get('title') and request.POST.get('content'):
            activity = Activity()
            activity.title = request.POST.get('title')
            activity.time = request.POST.get('time')
            activity.description = request.POST.get('content')

            activity.save()

            return redirect("activity:activity")

    else:
        return render(request, 'activity/createActivity.html')


class editActivity(TemplateView):
    template_name = 'activity/editActivity.html'

    def get_context_data(self, *args, **kwargs):
        activity = Activity.objects.get(pk=self.kwargs.get('pk'))
        context = super().get_context_data(*args, **kwargs)

        context['activity'] = activity

        return context


def updateActivity(request, *args, **kwargs):
    pk = kwargs.get('pk')

    activity = Activity.objects.get(pk=pk)

    title = request.POST['title']
    if request.POST['time']:
        time = request.POST['time']
    else:
        time = activity.time
    description = request.POST['content']

    activity.title = title
    activity.time = time
    activity.description = description

    activity.save()

    return HttpResponseRedirect(
        reverse("activity:activity"))


def deleteActcity(request, *args, **kwargs):
    pk = kwargs.get('pk')
    d_activity = Activity.objects.get(pk=pk)
    d_activity.delete()

    return HttpResponseRedirect(
        reverse("activity:activity"))

activity/templates/activity/a.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" type="text/css" href="/static/styles/about.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <div class="container">
        {% for i in activity  reversed %}

            <div class="box">
            <section class="hero is-primary">
                <div class="hero-body">
                    <p class="title">{{ i.title }}</p>

                    <p class="subtitle">{{ i.description }}</p>

                    <p class="subtitle">{{ i.time|date:"Y-m-d  H:i" }}</p>

                    {% if user.is_authenticated %}

                        <a href={%  url 'activity:edit_activity' pk=i.id %}>
                            <button type="button">Edit</button>
                        </a>


                    {% endif %}
                </div>
            </section>
        </div>

        {% endfor %}
    </div>
{% endblock content %}

activity/templates/activity/createActivity.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" type="text/css" href="/static/styles/edit_achievement.css">
<br><br><br><br>
<h1>Create Activity or News</h1><br>
    <form action="" method="POST" enctype="multipart/form-data" id="myForm">
        {% csrf_token %}
        Title: <input type="text" class="title-input" name="title" required/><br/><br>
        Time:
        <input type="datetime-local" class="title-input" id="activity_time" name="time" required>
        <br><br>
        Content: <br/>
        <textarea cols="57" rows="8" name="content" required></textarea><br/>
        <input type="submit" class="edit-button1" value="Post"/>
    </form>


    
<script>

    document.getElementById('myForm').addEventListener('submit', function (event) {
                event.preventDefault(); // Prevent the default form submission
    
                Swal.fire({
                    title: 'Are you sure?',
                    text: 'You are about to submit this form.',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, submit it!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        // If the user confirms, submit the form
                        document.getElementById('myForm').submit();
                    }
                });
            });
    </script>
{% endblock content %}

activity/templates/activity/editActivity.html
{% extends 'base.html' %}


{% block content %}
<link rel="stylesheet" type="text/css" href="/static/styles/edit_achievement.css">
<br><br><br><br>
<h1>Edit Activity or News </h1><br>
    <form action="{% url 'activity:update_activity' pk=activity.pk %}" method="POST" enctype="multipart/form-data" id="myForm">
        {% csrf_token %}
        Title:<br>
        <input name="title" value="{{ activity.title }}" class="title-input">
        <br><br>
        Time:
        <p class="subtitle">{{ activity.time|date:"Y-m-d  H:i" }}</p>
        <input type="datetime-local" id="activity_time" name="time" class="title-input">
        <br>

        Description:<br>
        <textarea name="content" class="title-input2">{{ activity.description }} </textarea>
        <br><br>
        <input type="submit" onclick="saveContent()" value="Accept" class="edit-button">

        <input type="button" onclick="deleteContent()" value="delete" class="edit-button1">
        <input type="button" onclick="cancel()" value="cancel" class="edit-button2">


    </form>

    <script>
        function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }

        function cancel() {
            window.location.href =
            {%  url 'activity:activity' %}
        }

        document.getElementById('myForm').addEventListener('submit', function (event) {
            event.preventDefault(); // Prevent the default form submission

            Swal.fire({
                title: 'Are you sure?',
                text: 'You are about to submit this form.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, submit it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // If the user confirms, submit the form
                    document.getElementById('myForm').submit();
                }
            });
        });

        function deleteContent() {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then((result) => {
                if (result.isConfirmed) {

                    fetch('{% url 'activity:delete_activity' pk=activity.pk %}')
                        .then(response => {
                            if (!response.ok) {
                                throw new Error('Network response was not ok');
                            }
                            return response.json();
                        })
                        .then(data => {
                            console.log(data.message);
                        })
                } else if (
                    /* Read more about handling dismissals below */
                    result.dismiss === Swal.DismissReason.cancel

                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Your imaginary file is safe :)',
                        'error'
                    )
                }
            }).then(function () {
                setTimeout(function () {
                    window.location.href =
                    {%  url 'activity:activity' %}
                }, 1000);
            })
        }

    </script>


{% endblock content %}

activity/templates/activity/index.html
{% extends 'base.html' %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var markdownContent = document.getElementById('markdown-content').innerText;
        var htmlContent = marked(markdownContent);
        document.getElementById('markdown-content').innerHTML = htmlContent;
    });
</script>
{% block content %}
<link rel="stylesheet" type="text/css" href="/static/styles/about.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <div class="container">
        <br>
        <br>
        <h1>Activities and News</h1>
        {% for i in activity  reversed %}

        <div class="box">
            <section class="overview-section">
                <div class="overview-text">
                    <h2 class="title">{{ i.title }}</h2>
    
                    <p class="subtitle" >{{ i.description }}</p>
                    <p class="subtitle">{{ i.time|date:"Y-m-d  H:i" }}</p>
                
                {% if user.is_authenticated %}

                        <a href={%  url 'activity:edit_activity' pk=i.id %}>
                            <button type="button" class="edit-button">Edit post</button>
                            <!-- <button type="button">Edit</button> -->
                        </a>
    
    
                    {% endif %}
                </div>
                <!-- </div> -->
            </section>
    
    
        </div>
        {% endfor %}
    </div>
{% endblock content %}