IUT_CS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('home/', views.home.as_view(), name='home_'),
                  path('mdeditor/', include('mdeditor.urls')),
                  path('blogs/', include('blogs.urls')),
                  path('achievements/', include('achievements.urls')),
                  path('activity/', include('activity.urls')),
                  path('executive_committee/', views.ExecutiveCommittee.as_view(), name='executive_committee'),
                  path('about/', views.about.as_view(), name='about'),
                  path('admin_panel/', include('admin_panel.urls')),
                  path('intra_events/', include('intra_university_event.urls')),
                  path('inter_events/', include('inter_university_event.urls')),
                  path('events/', views.events.as_view(), name='events'),
                  path('', views.home.as_view(), name='home'),
                  path('inter_events_and_participants/', views.inter_event_participants.as_view(), name='inter_events_and_participants'),
                  path('intra_events_and_participants/', views.intra_event_participants.as_view(), name='intra_events_and_participants'),
                  path('leaderboard/', views.leaderboard.as_view(), name='leaderboard'),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name='blogs'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create_blog/', views.createBlog, name='create_blog'),
    path('edit_blog/<int:pk>', views.editBlog.as_view(), name='edit_blog'),
    path('update_blog/<int:pk>', views.updateBlog, name='update_blog'),
    path('delete_blog/<int:pk>', views.deleteBlog, name='delete_blog'),
]

blogs/models.py
from django.db import models

# Create your models here.
from django.db import models
from mdeditor.fields import MDTextField

class Blogs(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    content = MDTextField()
    created_at = models.DateTimeField(auto_now_add=True)

blogs/forms.py
from django.forms import ModelForm


from blogs.models import Blogs

class BlogForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['title'].widget.attrs['class'] = 'form-control'
        self.fields['author'].widget.attrs['class'] = 'form-control'


    class Meta:
        model = Blogs
        fields = '__all__'

blogs/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView

from .models import Blogs
from .forms import BlogForm
# Create your views here.
def index(request):
    blog = Blogs.objects.all()
    context = {'blog': blog}

    return render(request, 'blogs/index.html', context)


def detail(request, pk):
    blog = Blogs.objects.get(pk=pk)
    context = {'blog': blog}

    return render(request, 'blogs/detail.html', context)


'''
def createBlog(request):
    form = BlogForm

    if request.method == 'POST':


        if request.POST.get('title') and request.POST.get('content'):
            blog = Blogs()
            blog.title = request.POST.get('title')
            blog.author = request.POST.get('author')
            blog.content = request.POST.get('content')

            blog.save()

            return redirect("blogs:blogs")

    else:
        
        return render(request, 'blogs/createBlog.html')

'''


def createBlog(request):
    form = BlogForm

    if request.method == 'POST':
        form = BlogForm(request.POST)

        if form.is_valid():
            form.save()

        return redirect("blogs:blogs")

    context = {'form': form}

    return render(request, 'blogs/createBlog.html',context)


class editBlog(TemplateView):
    template_name = 'blogs/editBlog.html'

    def get_context_data(self, *args, **kwargs):
        blog = Blogs.objects.get(pk=self.kwargs.get('pk'))
        context = super().get_context_data(*args, **kwargs)

        context['form'] = BlogForm(instance=blog)
        context['blog'] = blog

        return context


'''
class editBlog(TemplateView):
    template_name = 'blogs/editBlog.html'

    def get_context_data(self, *args, **kwargs):
        blog = Blogs.objects.get(pk=self.kwargs.get('pk'))
        context = super().get_context_data(*args, **kwargs)

        context['blog'] = blog

        return context
'''


def updateBlog(request, *args, **kwargs):
    pk = kwargs.get('pk')

    blog = Blogs.objects.get(pk=pk)

    title = request.POST['title']
    author = request.POST['author']

    content = request.POST['content']

    blog.title = title
    blog.author = author
    blog.content = content

    blog.save()

    return HttpResponseRedirect(
        reverse("blogs:blogs"))



def deleteBlog(request, *args, **kwargs):
    pk = kwargs.get('pk')
    d_blog = Blogs.objects.get(pk=pk)
    d_blog.delete()

    return HttpResponseRedirect(
        reverse("blogs:blogs"))


from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import markdown

blogs/templates/blogs/blogs.html
{% load staticfiles %}
<! DOCTYPE html>
<html lang = "en">
    <head>
        <meta http-equiv = "Content-Type" content = "text / html; charset = utf-8" />

    </head>
    <body>
        <form method = "post" action = "./">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <p> <input type = "submit" value = "post"> </p>
        </form>
    </body>
</html>

blogs/templates/blogs/createBlog.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<link rel="stylesheet" type="text/css" href="/static/styles/edit_achievement.css">
<br><br><br>
<h1>Create a blog </h1>
    <form action="" method="POST" enctype="multipart/form-data" id="myForm">
        {% csrf_token %}
            {{  form.media }}
            {{  form.as_p }}
        <!--
        Title: <input type="text" class="title-input"  name="title"  required/><br/><br>
        Author: <input type="text" class="title-input" name="author" required/><br/><br>
        Content: <br/>
        <textarea cols="57" rows="8" name="content" required></textarea><br/>
        -->
        <input type="submit" class="edit-button1" value="Post"/>

    </form>

    
<script>

    document.getElementById('myForm').addEventListener('submit', function (event) {
                event.preventDefault(); // Prevent the default form submission
    
                Swal.fire({
                    title: 'Are you sure?',
                    text: 'You are about to submit this form.',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, submit it!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        // If the user confirms, submit the form
                        document.getElementById('myForm').submit();
                    }
                });
            });
    </script>
{% endblock content %}

blogs/templates/blogs/detail.html
{% extends 'base.html' %}

{% load blog_extras %}

{% block content %}
<link rel="stylesheet" type="text/css" href="/static/styles/about.css">
    <!-- <div class="box">
        <section class="hero is-primary is-medium">
            <div class="hero-body">
                <p class="title">{{ blog.title }}</p>
                <p class="subtitle">{{ blog.created_at|date:"Y-m-d H:i" }}</p>
            </div>
        </section>

        <div class="content intro">
            <p>{{ blog.author }}</p>
        </div>

        <div class="content">
            {{ blog.content|convert_markdown|safe }}
        </div>
    </div> -->
    <br><br><br><br>
    <div class="box">
        <section class="overview-section">
            <div class="overview-text">
                <h1 class="title">{{ blog.title }}</h1>


                <p class="subtitle">{{ blog.created_at|date:"Y-m-d H:i" }}</p>


                    <p>{{ blog.author }}</p>



                    {{ blog.content|convert_markdown|safe }}


            </div>
            <!-- </div> -->
        </section>


    </div>
{% endblock %}

blogs/templates/blogs/editBlog.html
{% extends 'base.html' %}

{% load blog_extras %}

{% block content %}
    <style>
        /* Style to make input look like textarea */
        .textarea-like-input {
            border: 1px solid #ccc;
            padding: 5px;
            font-size: 16px;
            width: 300px; /* Adjust the width as needed */
            height: 100px; /* Adjust the height as needed */
            resize: none; /* Disable textarea resizing */
        }
    </style>


    <link rel="stylesheet" type="text/css" href="/static/styles/edit_achievement.css">
    <br><br><br>
    <h1>Edit Blog </h1>
    <form action="{% url 'blogs:update_blog' pk=blog.pk %}" method="POST" enctype="multipart/form-data" id="myForm">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}

        <input type="submit" value="Accept" class="edit-button">

        <input type="button" onclick="deleteContent()" value="delete" class="edit-button1">
        <input type="button" onclick="cancel()" value="cancel" class="edit-button2">


    </form>

    <!--
    <script>
        // Get references to the input field and the preview div
        const inputText = document.getElementById("inputText");
        const preview = document.getElementById("markdown");


        // Add an event listener to the input field to listen for changes
        inputText.addEventListener("input", updatePreview);


        // Function to update the preview
        function updatePreview() {
            const inputValue = inputText.value;
            console.log(inputValue)
            preview.textContent = inputValue;
        }


    </script>
    <script>
        function update(){
            fetch('{% url 'blogs:update_blog' pk=blog.pk %}')
                        .then(response => {
                            if (!response.ok) {
                                throw new Error('Network response was not ok');
                            }
                            return response.json();
                        })
                        .then(data => {
                            console.log(data.message);
                        }).then()
        }
    </script>
    -->


    <script>
        function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }

        function cancel() {
            window.location.href =
            {%  url 'blogs:blogs' %}
        }

        document.getElementById('myForm').addEventListener('submit', function (event) {
            event.preventDefault(); // Prevent the default form submission

            Swal.fire({
                title: 'Are you sure?',
                text: 'You are about to submit this form.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, submit it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // If the user confirms, submit the form
                    document.getElementById('myForm').submit();
                }
            });
        });

        function deleteContent() {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then((result) => {
                if (result.isConfirmed) {

                    fetch('{% url 'blogs:delete_blog' pk=blog.pk %}')
                        .then(response => {
                            if (!response.ok) {
                                throw new Error('Network response was not ok');
                            }
                            return response.json();
                        })
                        .then(data => {
                            console.log(data.message);
                        })
                } else if (
                    /* Read more about handling dismissals below */
                    result.dismiss === Swal.DismissReason.cancel

                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Your imaginary file is safe :)',
                        'error'
                    )
                }
            }).then(function () {
                setTimeout(function () {
                    window.location.href =
                    {%  url 'blogs:blogs' %}
                }, 1000);
            })
        }

    </script>


{% endblock content %}

blogs/templates/blogs/index.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" type="text/css" href="/static/styles/about.css">
    <br><br>
<h1>Blogs </h1>
    {% for i in blog reversed %}

    <div class="box">
        <section class="overview-section">
            <div class="overview-text">
                <h2 class="title">{{ i.title }}</h2>

                <p class="subtitle" >{{ i.author }}</p>
                <p class="subtitle">{{ i.created_at|date:"Y-m-d H:i" }}</p>

                <a href="{{ i.id }}"><class="read-more">Read more</a><br>

                {% if user.is_authenticated %}

                <a href='{% url 'blogs:edit_blog' pk=i.id %}'>
                    <button type="button" class="edit-button">Edit</button>
                </a>
            {% endif %}
            </div>
            <!-- </div> -->
        </section>


    </div>



    {% endfor %}
{% endblock content %}