IUT_CS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path("admin/", admin.site.urls),
                  path('home/', views.home.as_view(), name='home_'),
                  path('mdeditor/', include('mdeditor.urls')),
                  path('blogs/', include('blogs.urls')),
                  path('achievements/', include('achievements.urls')),
                  path('activity/', include('activity.urls')),
                  path('executive_committee/', views.ExecutiveCommittee.as_view(), name='executive_committee'),
                  path('about/', views.about.as_view(), name='about'),
                  path('admin_panel/', include('admin_panel.urls')),
                  path('intra_events/', include('intra_university_event.urls')),
                  path('inter_events/', include('inter_university_event.urls')),
                  path('events/', views.events.as_view(), name='events'),
                  path('', views.home.as_view(), name='home'),
                  path('inter_events_and_participants/', views.inter_event_participants.as_view(), name='inter_events_and_participants'),
                  path('intra_events_and_participants/', views.intra_event_participants.as_view(), name='intra_events_and_participants'),
                  path('leaderboard/', views.leaderboard.as_view(), name='leaderboard'),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name='blogs'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create_blog/', views.createBlog, name='create_blog'),
    path('edit_blog/<int:pk>', views.editBlog.as_view(), name='edit_blog'),
    path('update_blog/<int:pk>', views.updateBlog, name='update_blog'),
    path('delete_blog/<int:pk>', views.deleteBlog, name='delete_blog'),
]

inter_university_event/urls.py
from django.urls import path

from . import views

app_name = 'inter_event'

urlpatterns = [
    path('', views.index, name='inter_events'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create_inter_event/', views.createInter_event, name='create_event'),
    path('edit_inter_event/<int:pk>', views.editInter_event.as_view(), name='edit_event'),
    path('update_inter_event/<int:pk>', views.updateInter_event, name='update_event'),
    path('delete_inter_event/<int:pk>', views.deleteInter_event, name='delete_event'),
    path('team_registration/<int:pk>', views.team_registration, name='team_registration'),
    
]

'''

'''

inter_university_event/models.py
from django.db import models
from mdeditor.fields import MDTextField


# Create your models here.
class Inter_University_Event(models.Model):
    title = models.CharField(max_length=100)
    time = models.DateTimeField(blank=True)
    image = models.FileField(upload_to='inter_event_images', blank=True, null=True)
    maximum_member=models.IntegerField(blank=True)
    content = MDTextField()
    

class Team(models.Model):
    name = models.CharField(max_length=255)
    team_key = models.CharField(max_length=255,unique=True,blank=False)
    event = models.ForeignKey(Inter_University_Event, on_delete=models.CASCADE, related_name='teams')

    def __str__(self):
        return self.name

class Member(models.Model):
    name = models.CharField(max_length=255)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='members')
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    institute = models.CharField(max_length=100)

    def __str__(self):
        return self.name

inter_university_event/forms.py
from django.forms import ModelForm
from django import forms

from .models import Inter_University_Event

class InterUniversityEventForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)




    class Meta:
        model = Inter_University_Event
        fields = ['content']

inter_university_event/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView

from django.core.files.storage import FileSystemStorage

from .models import Inter_University_Event,Team,Member
from .forms import InterUniversityEventForm

import os
from datetime import datetime
import random
import string

from django.core.mail import send_mail
from IUT_CS.settings import EMAIL_HOST_USER

# Create your views here.
def index(request):
    inter_event = Inter_University_Event.objects.all()
    context = {'inter_event': inter_event}

    return render(request, 'inter_event/index.html', context)


def detail(request, pk):
    inter_event = Inter_University_Event.objects.get(pk=pk)
    context = {'inter_event': inter_event}

    return render(request, 'inter_event/detail.html', context)

'''
def createInter_event(request):
    if request.method == 'POST':
        if request.POST.get('title') and request.POST.get('content'):
            inter_event = Inter_University_Event()
            inter_event.title = request.POST.get('title')
            inter_event.time = request.POST.get('time')
            inter_event.content = request.POST.get('content')

            inter_event.save()

            return redirect("inter_event:inter_events")

    else:
        return render(request, 'inter_event/createinter_event.html')

'''



def createInter_event(request):
    form = InterUniversityEventForm
    if request.method == 'POST':
        form = InterUniversityEventForm(request.POST)

        if form.is_valid():
            if request.POST.get('title') and request.POST.get('content'):
                inter_event = Inter_University_Event()
                inter_event.title = request.POST.get('title')
                inter_event.time = request.POST.get('time')
                inter_event.maximum_member = request.POST.get('maximum_member')


                dir = "/media/"
                image = request.FILES['image']
                fss = FileSystemStorage()
                print(image.name)
                file = fss.save(image.name, image)
                file_url = fss.url(file)
                inter_event.image = dir + os.path.basename(file_url)

                content = form.cleaned_data['content']
                inter_event.content = content

                inter_event.save()

                return redirect("inter_event:inter_events")

    context = {'form': form}

    return render(request, 'inter_event/createinter_event.html', context)


class editInter_event(TemplateView):
    template_name = 'inter_event/editinter_event.html'

    def get_context_data(self, *args, **kwargs):
        inter_event = Inter_University_Event.objects.get(pk=self.kwargs.get('pk'))
        context = super().get_context_data(*args, **kwargs)

        context['form'] = InterUniversityEventForm(instance=inter_event)
        context['inter_event'] = inter_event

        return context


def updateInter_event(request, *args, **kwargs):
    pk = kwargs.get('pk')

    inter_event = Inter_University_Event.objects.get(pk=pk)

    title = request.POST['title']
    time = request.POST['time']
    maximum_member = request.POST['maximum_member']

    content = request.POST['content']

    inter_event.title = title
    if request.POST['time']:
        time = request.POST['time']
    else:
        time = inter_event.time

    dir = "/media/"
    image = request.FILES['image']
    fss = FileSystemStorage()
    print(image.name)
    file = fss.save(image.name, image)
    file_url = fss.url(file)
    inter_event.image = dir + os.path.basename(file_url)

    inter_event.time = time
    inter_event.content = content
    inter_event.maximum_member = maximum_member
    
    inter_event.save()

    return HttpResponseRedirect(
        reverse("inter_event:inter_events"))


def deleteInter_event(request, *args, **kwargs):
    pk = kwargs.get('pk')
    d_inter_event = Inter_University_Event.objects.get(pk=pk)
    d_inter_event.delete()

    return HttpResponseRedirect(
        reverse("inter_event:inter_events"))


def google_formInter_event(request, pk):
    template_name = 'inter_events/google_form.html'
    inter_event = Inter_University_Event.objects.get(pk=pk)
    context = {'inter_event': inter_event}

    return render(request, template_name, context)


def team_registration(request, pk):
    inter_event = Inter_University_Event.objects.get(pk=pk)
    context = {'inter_event': inter_event}

    if request.method == 'POST':
        if request.POST.get('team_name'):
            team = Team()
            team.name = request.POST.get('team_name')
            team.event = inter_event

            timestamp = int(datetime.timestamp(datetime.now()))
            random_string = ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))
            unique_key = f"{timestamp}-{random_string}"
            team.team_key = unique_key

            team.save()
            
            members=[]
            for i in range(0,inter_event.maximum_member):
                member = Member()
                member.team = team
                member.name = request.POST.get('member_'+ str(i) + '_name')
                member.email = request.POST.get('member_'+ str(i) + '_email')
                member.phone = request.POST.get('member_'+ str(i) + '_phone')
                member.institute = request.POST.get('member_'+ str(i) + '_institute')

                if len(member.name)!=0 and len(member.email)!=0 and len(member.phone)!=0 and len(member.institute)!=0:
                    member.save()
                    
            
                members.append(member)
            
            context = {'inter_event':inter_event}
            context['team']=team
            context['members']=members


            subject = 'Tnx for registration for'+str(inter_event.title) 
            message = str(team.name)+'\nThank you for registering on our event.\n'+ 'This is your team key: '+ str(team.team_key)
            from_email = EMAIL_HOST_USER
            recipient_list = []
            for mem in members:
                recipient_list.append(mem.email)  # Replace with the user's email address
            
            send_mail(subject, message, from_email, recipient_list)

            
            return redirect("inter_event:inter_events")
            
    else:
        return render(request, 'inter_event/team_registration_page.html', context)
    

inter_university_event/templates/inter_event/confirm_registration.html
{% extends 'base.html' %}

{% load times %}

{% block content %}


<link rel="stylesheet" type="text/css" href="/static/styles/edit_achievement.css">
<br>
<br>
<br>
<h1>Team Registration</h1>


<div class="box">
        <section class="">
            <p>Team Name: {{ team.name }}</p>
        </section>
</div>
    {% for i in  members %}
    
        {% if forloop.first %}
        <div class="box">
            <section class="">
                <p>Team Leader Information</p>
                <p>Name: {{ i.name }}</p>
                <p>Email: {{ i.email }}</p>
                <p>Contact No: {{ i.phone }}</p>
                <p>Institute: {{ i.institute }}</p>
            </section>
        </div>
        {% else %}
        <div class="box">
            <section class="">
                <p>Name: {{ i.name }}</p>
                <p>Email: {{ i.email }}</p>
                <p>Contact No: {{ i.phone }}</p>
                <p>Institute: {{ i.institute }}</p>
            </section>
        </div>

        {% endif %}
    
    {% endfor %}

<form action="" enctype="multipart/form-data" id="myForm">
    {% csrf_token %}
    Confirm:
    <input type="checkbox" id="myCheckbox" name="confirm">
    <br>
        <input type="submit" value="Submit" />
</form>


    
{% endblock %}

inter_university_event/templates/inter_event/createinter_event.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" type="text/css" href="/static/styles/edit_achievement.css">
    <br>
    <br>
    <br>
    <br>
    <h1>Create a Inter Uni Event </h1>
    <form action="" method="POST" enctype="multipart/form-data" id="myForm">
        {% csrf_token %}
    <br><b>Title:</b><br> <input type="text" class="title-input" name="title" required/><br/>
<br><b> Time:</b><br>
        <input type="datetime-local" class="title-input"id="activity_time" name="time" required>
        
        <br>
    <br><b> Maximum Number of Member:</b><br>
        <input type="number" class="title-input" id="maximum_member" name="maximum_member">

        <br>
        <b>Image:</b><br>
        <div class="overview-image">
            <img id="imagePreview" src="{{ intra_event.image }}">
        </div>

        <label for="image" class="file-upload">
            <class
            ="icon">Choose File
            <input name="image" id="image" type="file" accept="image/*" class="form-control" onchange="previewImage()" required>
        </label>

        {{ form.media }}
        {{ form.as_p }}
        
        <br>
        <input type="submit" value="Post" class="edit-button1"/>

    </form>


    
    <script>
        function previewImage() {
            var input = document.getElementById('image');
            var preview = document.getElementById('imagePreview');

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    preview.src = e.target.result;
                    preview.style.display = 'block';
                };

                reader.readAsDataURL(input.files[0]);
            } else {
                preview.style.display = 'none';
            }
        }

    </script>

    
<script>

    document.getElementById('myForm').addEventListener('submit', function (event) {
                event.preventDefault(); // Prevent the default form submission
    
                Swal.fire({
                    title: 'Are you sure?',
                    text: 'You are about to submit this form.',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, submit it!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        // If the user confirms, submit the form
                        document.getElementById('myForm').submit();
                    }
                });
            });
    </script>

{% endblock content %}

inter_university_event/templates/inter_event/detail.html
{% extends 'base.html' %}

{% load blog_extras %}

{% block content %}
<br>
    <br>
    <br>
    <br>
    <link rel="stylesheet" type="text/css" href="/static/styles/about.css">
    <div class="box">
        <section class="overview-section">
            <div class="overview-text">
                <h2 class="title">{{ inter_event.title }}</h2>
                <p class="subtitle">{{ inter_event.time|date:"Y-m-d H:i" }}</p>
                <br>
                Maximum Member:
                <h2 class="subtitle">{{ inter_event.maximum_member }}</h2>
                <a href='{% url 'inter_event:team_registration' pk=inter_event.id %}'>
                <button type="button" class="edit-button">click here for registration</button>
            </a>
            </div>
            <div class="overview-image">
                <img src="{{ inter_event.image }}">
            </div>
            
        

        
    </div>
        <div class="box">
            
                {{ inter_event.content|convert_markdown|safe }}
            </div>
        
    </section>

{% endblock %}

inter_university_event/templates/inter_event/editinter_event.html
{% extends 'base.html' %}

{% load blog_extras %}

{% block content %}

<link rel="stylesheet" type="text/css" href="/static/styles/edit_achievement.css">
    <style>
        /* Style to make input look like textarea */
        .textarea-like-input {
            border: 1px solid #ccc;
            padding: 5px;
            font-size: 16px;
            width: 300px; /* Adjust the width as needed */
            height: 100px; /* Adjust the height as needed */
            resize: none; /* Disable textarea resizing */
        }
    </style>

    <br>
    <br>
    <br>
    <h1>Edit a Inter Uni Event </h1>
    <form action="{% url 'inter_event:update_event' pk=inter_event.pk %}" method="POST" enctype="multipart/form-data" id="myForm">
        {% csrf_token %}
        <b>Title:</b><br>
        <input name="title" class="title-input" value="{{ inter_event.title }}">
        <br><br>
    <b>Time:</b><br>
        <p class="subtitle">{{ inter_event.time|date:"Y-m-d  H:i" }}</p>
        <input type="datetime-local" class="title-input" id="time" name="time">
        <br>
        <br>
    <b>Maximum Number of Member:</b>
    <br>
        <input type="number" class="title-input" id="maximum_member" name="maximum_member" value="{{ inter_event.maximum_member }}">


        <br>
        <b>Image:</b><br>
        <div class="overview-image">
            <img id="imagePreview" src="{{ inter_event.image }}" >
        </div>

        <label for="image" class="file-upload">
            <class
            ="icon">Choose File
            <input name="image" id="image" type="file" accept="image/*" class="form-control" onchange="previewImage()" required>
        </label>

        {{ form.media }}
        {{ form.as_p }}


        <br><br>
        <input type="submit" value="Accept" class="edit-button">

        <input type="button" onclick="deleteContent()" value="delete" class="edit-button1">
        <input type="button" onclick="cancel()" value="cancel" class="edit-button2">


    </form>
    

    <script>
        function previewImage() {
            var input = document.getElementById('image');
            var preview = document.getElementById('imagePreview');

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    preview.src = e.target.result;
                    preview.style.display = 'block';
                };

                reader.readAsDataURL(input.files[0]);
            } else {
                preview.style.display = 'none';
            }
        }

    </script>
    

    <script>
        function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }

        function cancel() {
            window.location.href =
            {%  url 'inter_event:inter_events' %}
        }

        document.getElementById('myForm').addEventListener('submit', function (event) {
            event.preventDefault(); // Prevent the default form submission

            Swal.fire({
                title: 'Are you sure?',
                text: 'You are about to submit this form.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, submit it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // If the user confirms, submit the form
                    document.getElementById('myForm').submit();
                }
            });
        });

        function deleteContent() {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true
            }).then((result) => {
                if (result.isConfirmed) {

                    fetch('{% url 'inter_event:delete_event' pk=inter_event.pk %}')
                        .then(response => {
                            if (!response.ok) {
                                throw new Error('Network response was not ok');
                            }
                            return response.json();
                        })
                        .then(data => {
                            console.log(data.message);
                        })
                } else if (
                    /* Read more about handling dismissals below */
                    result.dismiss === Swal.DismissReason.cancel

                ) {
                    swalWithBootstrapButtons.fire(
                        'Cancelled',
                        'Your imaginary file is safe :)',
                        'error'
                    )
                }
            }).then(function () {
                setTimeout(function () {
                    window.location.href =
                    {%  url 'inter_event:inter_events' %}
                }, 1000);
            })
        }

    </script>

    
<script>

    document.getElementById('myForm').addEventListener('submit', function (event) {
                event.preventDefault(); // Prevent the default form submission
    
                Swal.fire({
                    title: 'Are you sure?',
                    text: 'You are about to submit this form.',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, submit it!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        // If the user confirms, submit the form
                        document.getElementById('myForm').submit();
                    }
                });
            });
    </script>

{% endblock content %}

inter_university_event/templates/inter_event/google_form.html
{% extends 'base.html' %}


{% block content %}
    <br>
    <br>
    <br>
    <br>
    <div >
        <iframe src="{{ inter_event.google_form_link }}"
                width="640" height="800" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
    </div>
{% endblock content %}

inter_university_event/templates/inter_event/index.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <br>
    <br>
    <br>
    <link rel="stylesheet" type="text/css" href="/static/styles/about.css">
    <div class="h1" style="text-align: center;">
      <h1 class="site-title">Inter University Events</h1>
  </div>
    {% for i in inter_event reversed %}

        <div class="box">
            <section class="overview-section">
                <div class="overview-text">
                    <h2 class="title">{{ i.title }}</h2>
                    <p class="subtitle">{{ i.time|date:"Y-m-d H:i" }}</p>
                    <br>
                    Maximum Member:
                    <h2 class="subtitle">{{ i.maximum_member }}</h2>
                    <a href="{{ i.id }}"><b><u>Read more</u></b></a><br>
                <a href='{% url 'inter_event:team_registration' pk=i.id %}'>
                    <button type="button" class="edit-button">click here for registration</button>
                </a>
                </div>
                <div class="overview-image">
                    <img src="{{ i.image }}">
                    {% if user.is_authenticated %}
    
                    <a href='{% url 'inter_event:edit_event' pk=i.id %}'>
                        <button type="button" class="edit-button">Edit post</button>
                    </a>
    
    
                    {% endif %}
                </div>
                
            </section>

            
        </div>
          

    {% endfor %}

    
{% endblock content %}

inter_university_event/templates/inter_event/intra_event.html
{% load staticfiles %}
<! DOCTYPE html>
<html lang = "en">
    <head>
        <meta http-equiv = "Content-Type" content = "text / html; charset = utf-8" />

    </head>
    <body>
        <form method = "post" action = "./">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <p> <input type = "submit" value = "post"> </p>
        </form>
    </body>
</html>

inter_university_event/templates/inter_event/team_registration_page.html
{% extends 'base.html' %}

{% load times %}

{% block content %}

input, select, textarea{
    color: #ff0000;
}

<link rel="stylesheet" type="text/css" href="/static/styles/edit_achievement.css">
<br>
<br>
<br>
<h1>Team Registration</h1>

<form action="" method="POST" enctype="multipart/form-data" id="myForm">
    {% csrf_token %}

    <div class="box">
        <section class="">
            <b>Team Name</b>:<br>
             <input type="text" name="team_name" class="title-input" required/><br/>
        </section>
    </div>
    {% for i in  inter_event.maximum_member|times %}
    <div class="box">
        <section class="">
            
            {% if i is 0 %}
        <b>Team Leader Information:</b> <br>
            <br>
        <b>Name*:</b><br>
            <input type="text" name="member_{{ i }}_name" class="title-input" required/><br/>
        <b>Email*:</b><br>
            <input type="email" name="member_{{ i }}_email" class="title-input" required/><br/>
            <b>Contact Number*:</b><br>
            <label for="member_{{ i }}_phone">+880</label>
            <input type="tel" name="member_{{ i }}_phone" class="title-input" id="member_{{ i }}_phone" required/><br/>
        <b>Institute*:</b><br>
            <input type="text" name="member_{{ i }}_institute" class="title-input" required/><br/>

            
            {% else %}
        <b> Member {{ i|add:1 }} Information:</b> <br>
            <br>
        <b>Name:</b><br>
            <input type="text" name="member_{{ i }}_name" class="title-input"/><br/>
        <b>Email:</b><br>
            <input type="email" name="member_{{ i }}_email" class="title-input"/><br/>
            <b>Contact Number:</b><br>
<label for="member_{{ i }}_phone">+880</label>
<input type="tel" name="member_{{ i }}_phone" class="title-input" id="member_{{ i }}_phone" /><br/>
        <b>Institute:</b><br>
            <input type="text" name="member_{{ i }}_institute" class="title-input"/><br/>
            {% endif %}
            
        </section>
    </div>

    
    {% endfor %}

    
        
        
            <input type="checkbox" id="myCheckbox" name="confirm" required>
            <b>  Check before submit</b>
            
   
    <br>
        <input type="submit" class ="edit-button1"value="Submit" />
</form>

<script>

document.getElementById('myForm').addEventListener('submit', function (event) {
            event.preventDefault(); // Prevent the default form submission

            Swal.fire({
                title: 'Are you sure?',
                text: 'You are about to submit this form.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, submit it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // If the user confirms, submit the form
                    document.getElementById('myForm').submit();
                }
            });
        });
</script>

{% endblock %}